development:
 bcrypt:
  salto: 10
  secretKey: myKey
 database:
  pg:
   host: 'localhost'
   user: 'postgres'
   port: 5432
   password: "sa"
   database: "tienda-online"
   max: 20
   idleTimeoutMillis: 30000
   connectionTimeoutMillis: 2000
  typeorm:
   type: "postgres"
   host: "localhost"
   port: 5432
   username: "postgres"
   password: "sa"
   database: "tienda-online"
   logging: false
   synchronize: true

production:
 bcrypt:
  salto: 10
  secretKey: myKey
 database:
  db: 'prod_db'
  user: 'dbuser'
  password: 'pass'
 cache:
  dir: 'static'